### ISSUE TITLE
Wrong Formatt?

### ISSUE THREAD

**Issue by Maxiskw** [ItIckeYd/VodRecovery#11]
I dont know much about the code and I want to know if I am doing it right.

![2](https://user-images.githubusercontent.com/105172352/167312483-2c233412-53be-4bd6-a339-d13c1eb26fb5.jpg)

and after I ran it 

![3](https://user-images.githubusercontent.com/105172352/167312485-e372002b-f995-467e-a675-afbd422080b3.jpg)

please help ty

**Comment by Maxiskw** [comment]
https://twitchtracker.com/a_seagull/streams/40777820075

**Comment by ItIckeYd** [comment]
@Maxiskw im not sure what you did?.. the first screen shot looks like your trying to actually edit the code? No need to edit the code.. you should just run it as is

**Comment by Maxiskw** [comment]
I am super dumb ok I got it now OMG
