### ISSUE TITLE
script crash

### ISSUE THREAD

**Issue by youngkiller1988** [ItIckeYd/VodRecovery#22]
![py](https://user-images.githubusercontent.com/82237017/169426736-85400cc1-0f28-48ea-918c-b3128d760270.png)
is this right because every time i hit enter the program runs for about 10 seconds and just closes

**Comment by ItIckeYd** [comment]
@youngkiller1988 you should run in an ide so the console stays open.. 

You can put input(“”) at the bottom of the script and it will stay open until you hit a key.
