### ISSUE TITLE
script not finding any vod

### ISSUE THREAD

**Issue by youngkiller1988** [ItIckeYd/VodRecovery#25]
says there are no vods even though the updated twitch recover finds them not sure what im doing wrong

**Comment by ItIckeYd** [comment]
@youngkiller1988 provide example please.

**Comment by youngkiller1988** [comment]
![Screenshot 2022-05-20 234311](https://user-images.githubusercontent.com/82237017/169634174-1849979f-39f1-4da4-a331-2d70cdb10e5e.png)
![Screenshot 2022-05-20 234420](https://user-images.githubusercontent.com/82237017/169634187-c0ec47bc-9378-4b2f-96d7-ee647b29352a.png)
first shot is your script second is the updated twitch recover
for some reason the python script says no vods on all the ones i try

**Comment by ItIckeYd** [comment]
@youngkiller1988 Its based off local timezone.. If you are UTC-3 you need to minus 3 hours from the UTC start time that twitchtracker shows. 

If you are UTC+3 you need to add 3 hours to the UTC time twitchtracker shows.

https://d1m7jfoe9zdc1j.cloudfront.net/e8092fe2c412a1aa1833_jinnytty_46424831421_1652871680/chunked/index-dvr.m3u8
https://d2vjef5jvl6bfs.cloudfront.net/e8092fe2c412a1aa1833_jinnytty_46424831421_1652871680/chunked/index-dvr.m3u8

above are the links.. do not contain muted segments.

**Comment by youngkiller1988** [comment]
i still cant get it to work can you do a screen shot that shows everything in place right before you hit enter so i can see how you have the data put in

**Comment by ItIckeYd** [comment]
@youngkiller1988 Where do you live?

**Comment by youngkiller1988** [comment]
usa florida

**Comment by ItIckeYd** [comment]
@youngkiller1988

Ok Florida timezones:

CDT - UTC-5
EDT - UTC-4

Knowing this... the start time of the vod is Wed, May 18, 11:01 UTC 

that means depending on your timezone:  
CDT - the start time becomes 06:01:00
EDT - the start time becomes 07:01:00

Try both.. one should work if the timezone that we are using is correct.

**Comment by youngkiller1988** [comment]
thank you the 07 worked so when ever i recover a vod just subtract 4 hours right

**Comment by ItIckeYd** [comment]
@youngkiller1988 Indeed.

**Comment by ItIckeYd** [comment]
#67
