### ISSUE TITLE
Wondering if it's still possible to recover these vods

### ISSUE THREAD

**Issue by Graydenn** [ItIckeYd/VodRecovery#29]
Streamer: https://streamscharts.com/channels/willly/streams

Only the most recent one seems to be downloadable. This streamer was banned.

**Comment by ItIckeYd** [comment]
@Graydenn Need to be more specific.. there is 6+ pages of vods which ones are you talking about?

**Comment by Graydenn** [comment]
As many of the recent ones as possible. He was going to edit them into videos.

**Comment by ItIckeYd** [comment]
@Graydenn You will need to run the script multiple times.. pretty much the only way to check.

**Comment by Graydenn** [comment]
You mean to check for each one? So far I've done about five with no luck.

**Comment by ItIckeYd** [comment]
@Graydenn Yes, Just make sure you are inputting the values correctly.

- Local timezone
- 00 value for seconds
- vod id from one of the three analytical sites.

**Comment by Graydenn** [comment]
Unfortunately I am, got the vod for the most recent stream. None of the other ones though

**Comment by ItIckeYd** [comment]
@Graydenn Yeah, I'm only able to get first one. Sorry.. twitch must have removed them already.
