### ISSUE TITLE
problem with the running the script

### ISSUE THREAD

**Issue by ceberios** [ItIckeYd/VodRecovery#31]
I have an issue with running the script
here is the example I tested https://www.twitch.tv/videos/1309586313 and here is my timezone : W. Central Africa Standard Time (UTC+01:00) and I also downloaded the CSV file from here : https://sullygnome.com/channel/panterochka_/streams
so I open RecoverVod.py and then 
Please choose an option: 1
Enter streamer name: Panterochka_
Enter vod id: 39358041639
Enter VOD timestamp (YYYY-MM-DD HH:MM:SS): 2022-05-26 16:21:00
and here's what I get : 
Vod is 1 days old. If the vod is older then 60 days chances of recovery are slim.
No vods found using current domain list.
what did I do wrong

**Comment by ItIckeYd** [comment]
@ceberios you need to use the vod id from twichtracker, sullygnome, streamscharts.

**Comment by ItIckeYd** [comment]
@ceberios just an extra note for the CSV file. You must open the CSV and save it.. if you get a prompt from excel click "yes". The save ensures formatting of the CSV is correct. Once done the script should run as expected.

**Comment by ceberios** [comment]
wow it actually worked this time dude thank you so much for this script
but to be completly honest with you ? I still don't know wtf I did wrong XD (I'm dumb) so this time all I changed from the last time is:
- the twitchtracker and sullygnome timezone to [UTC Coordinated Universal Time (+0)] instead of (UTC+1)
and added 1 hour in the script so from for example 15:21 in twitchtracker to 16:21:00 in the script
maybe this will help someone who had same problem 
I also found this thread helpful : https://github.com/ItIckeYd/VodRecovery/issues/28

**Comment by ItIckeYd** [comment]
@ceberios oh whoops, apologies I read the issue wrong. Glad you got it to work though! 

Let me know if you have any other questions.

**Comment by ItIckeYd** [comment]
#67
