### ISSUE TITLE
Clip recovery is very slow

### ISSUE THREAD

**Issue by JoePatty711** [ItIckeYd/VodRecovery#32]
Very new at this, so forgive me if this is a stupid question. Im using the clip retrieval for this script (im using it in pycharm) and I noticed in comparison to old twitch recover program with the wfuzz integration, it is about 20x slower to retrieve clip URLs. Is there any easy way of integrating wfuzz into this particular python script? im kind of out of my league on this one.

Thank you by the way for this script, the vod retrieval has been very handy, and gain, sorry if this is a dumb question, im trying to learn as I go and any info would be helpful.

**Comment by ItIckeYd** [comment]
@JoePatty711 You can increase it if you want.. totally up to you. I set it to take 200 url's at a time. Personally I usually set it at 500 but thought 200 might be less error prone when used by others.


```
def get_valid_clips_urls(clip_list, reps):
    valid_counter = 0
    valid_clip_url_list = []
    all_clip_url_list = []
    max_url_list_length = 200 **--Change to whatever you want..**  
    current_list = clip_list
    with ThreadPoolExecutor(max_workers=100) as pool:
        for i in range(0, len(clip_list), max_url_list_length):
            batch = current_list[i:i + max_url_list_length]
            response_list = list(pool.map(return_request_head, batch))
            for x in response_list:
                all_clip_url_list.append(x.url)
                if x.status_code == 200:
                    valid_counter = valid_counter + 1
                    valid_clip_url_list.append(x.url)
                    print(str(valid_counter) + " Clip(s) Found")
            print(str(len(all_clip_url_list)) + " of " + str(round(reps / 2)))
    return valid_clip_url_list
```

there probably is a way to implement wfuzz but I will not be doing so as this allows the script to be used without any additional software or downloads which is what I was aiming for.

**Comment by JoePatty711** [comment]
thank you for this info! this definitely helps a bit!

And so when I ran the old twitch recover program with wfuzz, It checked 11,000 possible links in under 3 minutes. While running this python script simultaneously, it was only through about 1,000 in the same time. This is why I was wondering for efficiency. Still a great script nonetheless and I appreciate your work and info. Thanks again!

**Comment by ItIckeYd** [comment]
@JoePatty711 Yeah, no problem.. I just timed a 5 hour vod and it check 19,700 urls in 4 minutes 55 seconds.
