### ISSUE TITLE
Request connection failing

### ISSUE THREAD

**Issue by ffedericode** [ItIckeYd/VodRecovery#35]
During the recover clips feature, i keep getting a "connection interrupted" on connectionpool.py

**Comment by ItIckeYd** [comment]
@ffedericode Yes, I'm aware of this issue.. Are you using the latest code? If not I would highly recommend getting the latest.

**Comment by ffedericode** [comment]
uh great! yes i just downloaded your last update. it was working, but after 3 minutes (a few of clips was found, but i can't see em) it stopped!

**Comment by ItIckeYd** [comment]
@ffedericode Can you provide vod link?

**Comment by ffedericode** [comment]
https://twitchtracker.com/stupidohotelshow/streams/39472908920 trying to recover this vod or clips related

**Comment by ItIckeYd** [comment]
@ffedericode I will attach file with all clip links included... as a workaround for now.

**Comment by ffedericode** [comment]
love it. thank you. i'll wait for you!

if i suggest you... i always have problem with the timezone, i think you should implement the same feature of TwitchRecover and get automatically those info just giving you a twitchtracker/sullygnome link. 

(ps: if i can ask, can you check if last ju10506's vod is downloadable? this is the link: https://twitchtracker.com/ju10506/streams/39333075047 )

have a nice day, thank you for your service. you're a king.
let me know :)

**Comment by ItIckeYd** [comment]
[39472908920_log.txt](https://github.com/ItIckeYd/VodRecovery/files/8832115/39472908920_log.txt)

See attached file for all clips of that stream - 154,358 url's checked.

**Comment by ItIckeYd** [comment]
@ffedericode I was unable to recover https://twitchtracker.com/ju10506/streams/39333075047.

**Comment by ItIckeYd** [comment]
Found a solution by implementing grequests. 

[grequests](https://pypi.org/project/grequests/) - allows you to use Requests with Gevent to make asynchronous HTTP Requests easily 

1st test - 4 hour 15 minute vod - No connection errors (Tried multiple times)
2nd test - 20 hour 53 minute vod - No connection errors 

Code will be updated by Sunday, June 5th.

Note: HTTP requests are dependent on CPU usage and connection. Depending on computer hardware/internet connection you may receive connection errors. I will ensure to show where to change in the code to reduce the load and allow full usage.

**Comment by ItIckeYd** [comment]
Removing urgent label as solution was found as noted in above comment.

**Comment by ffedericode** [comment]
excellent job dude, i'm gonna test it during the weekend! thank you

**Comment by ItIckeYd** [comment]
@ffedericode @lol1337123123 Clip recovery method changed and pushed to main branch. As far as my testing goes.. I have never gotten a connection failure and recovery seems to be on average 20 seconds faster per 30 minute vod.

**Comment by ffedericode** [comment]
just tested... it works! thank you!

**Comment by ItIckeYd** [comment]
Closing issue as no reports of connection failures or slowing of script have been reported.
