### ISSUE TITLE
Instant crash and log empty

### ISSUE THREAD

**Issue by lol1337123123** [ItIckeYd/VodRecovery#36]
Hey, whenever I run the clip recovery and it finishes, i press "Y" on both prompts so it downloads the clips, but instead it instantly crashes and then I check the .txt and it's empty.
Newest python version and pip installed.

Halp

**Comment by ItIckeYd** [comment]
@lol1337123123 were there any clips found? Have you tried inputting "y" for the first prompt and "n" for the second and checking the file without downloading to see if the file is empty?

**Comment by lol1337123123** [comment]
I will try the "y" then "n" thing now, yes 35+ clips found on this particular example. It happens with every single one I try.

**Comment by lol1337123123** [comment]
35 clips found logged but nothing is in the .txt

**Comment by lol1337123123** [comment]
:((((

**Comment by lol1337123123** [comment]
Yes 35 clips found, another friend tried and he has the full log .txt the tool is not working for me at all....

**Comment by ItIckeYd** [comment]
@lol1337123123 send twitchtracker link please.

**Comment by lol1337123123** [comment]
Did a clean reinstall and thorough setup, now it works. My bad.

**Comment by ItIckeYd** [comment]
@lol1337123123 sounds good.
