### ISSUE TITLE
Speeding up the process

### ISSUE THREAD

**Issue by lol1337123123** [ItIckeYd/VodRecovery#37]
Hey, just wanted to know if you are currently working on a method to speed up the script, particularly clip recovery?
Currently it takes 12-15 minutes ish for a 30 minute long vod for it to crawl all the URLs and multi-instancing is not stable.

**Comment by ItIckeYd** [comment]
@lol1337123123 thats not right. For me it takes about 5 minutes to get all clips for a 3 hour 15 minute vod.

**Comment by lol1337123123** [comment]
It hardly uses 10-15% of my cpu based on task manager and my internet is very decent, although I am also on VPN, but my upload speed while on vpn is still:
318mbps download, 70mbps upload. Any advice? It's literally working ultra slow for me would be nice to speed it up somehow.

**Comment by ItIckeYd** [comment]
@lol1337123123 no idea. I have 20mb down... are you actually timing it or are you guessing and throwing out a very high number.

**Comment by lol1337123123** [comment]
Yup gotcha, I'm timing it currently on a 2 hour 45 minute vod, will get back to you although it seems slow.

**Comment by ItIckeYd** [comment]
@lol1337123123 are you sure its a 30 minute vod? took 40 seconds for me.

**Comment by lol1337123123** [comment]
Currently at 2600 out of 11900 URL on a 2 hour 45 minute VOD, so far 5 minutes 30 seconds has elapsed :(((((

**Comment by ItIckeYd** [comment]
@lol1337123123 What are you using to run? Pycharm, CMD, visual studio code?

**Comment by lol1337123123** [comment]
CPU usage for python less than 5%, memory less than 10%. I'm using python 3.10 to run it

**Comment by ItIckeYd** [comment]
twitchtracker link?

**Comment by lol1337123123** [comment]
https://streamscharts.com/channels/lauraeclipsetv/streams/46534705661

**Comment by lol1337123123** [comment]
Yeah I don't know, my friend who is using a lot worse internet speed and worse PC specs is getting 2x my speed at least... idk whats goin' on

**Comment by lol1337123123** [comment]
It's about a 1 minute-1 minute 30secs, for every 600 URLs on avg...

**Comment by ItIckeYd** [comment]
@lol1337123123 finished in 2 minutes 7 seconds. Id download an actual IDE and run it... like pycharm or visual studio code and see if it makes a difference.

That vod does not contain any clips.. just so you don't have to wait 20 minutes for it to stop.

**Comment by lol1337123123** [comment]
Awesome bud, I'll dl pycharm now and run it and report back.

**Comment by lol1337123123** [comment]
Just ran it in visual studio code, it's still just as slow about 1 min  & 15-30 secs per 600 URLs :/

**Comment by ItIckeYd** [comment]
@lol1337123123 Very interesting. Sorry but I don't really have an answer. I know i'm using python 3.8.. but I doubt that would make any difference.

**Comment by ItIckeYd** [comment]
@lol1337123123 I'm going to update the code within the next day or two due to to a different issue... using a different method for retrieving clips. Ill tag you when completed and you can try again (hopefully it makes a difference).

**Comment by lol1337123123** [comment]
Fingers crossed. Thanks homie.

**Comment by ItIckeYd** [comment]
#35 Referencing as related issue.. Closing this issue. Ill use the other one as the main issue.
