### ISSUE TITLE
Problem with recovering 0-1day vod

### ISSUE THREAD

**Issue by Tsuk00** [ItIckeYd/VodRecovery#38]
https://twitchtracker.com/carolzinhasg/streams/46530370077

I'm trying to recovery this vod, but no luck, it's 0 day right now so should be easier to recover?
I also tried on this vod -> https://twitchtracker.com/carolzinhasg/streams/46528453405
on the first time didn't work, but on the second time i finally got the vod(and was not even deleted)
Can someone help recover this vod? -> https://twitchtracker.com/carolzinhasg/streams/46530370077

**Comment by ItIckeYd** [comment]
46528453405 -

https://d2vjef5jvl6bfs.cloudfront.net/6bf9f29ea27b0a1b3794_carolzinhasg_46528453405_1654282734/chunked/index-dvr.m3u8
Vod does NOT contain muted segments

I was unable to recover 46530370077 most likely it just doesn't exist anymore.

**Comment by Tsuk00** [comment]
The 46528453405 i manage to get on the second try, but 46530370077 is what i really want.

Even after less than 1-2 days a vod can be gone like that?

**Comment by ItIckeYd** [comment]
@Tsuk00 Its dependent on a lot of factors.. but yes it is possible the vod does not exist after 1-2 days. 

If the streamer did not save the vod initially then it would not exist. If twitch has deleted the vod it also would not exist.. the script can only recover what exists on the domains listed in the script.
