### ISSUE TITLE
Clip Suggestions

### ISSUE THREAD

**Issue by Infinitay** [ItIckeYd/VodRecovery#40]
### Recover Clips Menu

Might I suggest being a little more specific in the menu options? Something like
```
1. Recover all clips from a single VOD
2. Find random clips from a single VOD
3. Bulk recover clips from SullyGnome export
```

### Find Random Clips

When trying this feature out I noticed that it seemed a bit slow. I compared it against bulk recover, although looking back I suppose I also could have done "recover all clips", and it _seemed_ faster. I'm not sure if this was placebo or not due to having to being prompted for a new random clip or not. Nonetheless, I looked into the code and if I am understanding correctly, [#get_random_clips](https://github.com/ItIckeYd/VodRecovery/blob/2d1a97eb6fe30d4368fa7db4f194178ec557418a/RecoverVod.py#L281) was not refactored to use `grequests` as the other parts of the code were? IIRC you mentioned that you improved the performance of parts elsewhere by moving over to `grequests`. Would be nice if the same could be done here, assuming what I said was correct.

### Downloading All Clips

https://github.com/ItIckeYd/VodRecovery/blob/2d1a97eb6fe30d4368fa7db4f194178ec557418a/RecoverVod.py#L352

What is the purpose of generating a uuid for the file names? The original file names on Twitch ([#get_all_clip_urls](https://github.com/ItIckeYd/VodRecovery/blob/2d1a97eb6fe30d4368fa7db4f194178ec557418a/RecoverVod.py#L214) should already be unique enough, not to mention you add the streamer's name as a prefix. That sequence alone should be unique enough and it will preserve the chronological sequence in which the clips were saved with respect to the offset.

Also, it would be nice to either download the clips in the current working directory instead of user documents if you don't wish to prompt the user instead for the location. I would imagine the first place anyone would check is the working directory if there is no indication on where the files where saved.

**Comment by ItIckeYd** [comment]
@Infinitay thank you for the suggestions. I am going to update the options with what you provided as I think it's a much better wording. As for the random clip recovery.. I had not noticed any major speed increase and as far as I know I have not had any issues with requests connection failing therefore I was not going to update the method of retrieval as I thought it was sufficient. As that is obviously not the case I will make that update as well.

Thanks again.

Should be implemented in the next few days.
