### ISSUE TITLE
Remove generated guid appended onto file names of downloaded clips

### ISSUE THREAD

**Issue by Cccrrypt** [ItIckeYd/VodRecovery#42]
Is there any way of saving the clips with their relevant offset number alongside/instead of the seemingly random naming code that follows the VOD id?   eg:
Current clips naming format:    XQC_6969696969_0fc791d9
Proposed/requested format:    XQC_6969696969_7590 (the number being the url offset clip is downloaded from)

This should help finding specific url for clip you like in the log files saved.

**Comment by ItIckeYd** [comment]
@Cccrrypt I can remove the functionality of generating guid values.. You are the second person to ask this so I will do so.

**Comment by ItIckeYd** [comment]
@Cccrrypt Guid generation removed. Offset of clips now retained in filename as suggested.
