### ISSUE TITLE
investigate building an executable

### ISSUE THREAD

**Issue by lol1337123123** [ItIckeYd/VodRecovery#43]
Hi, so just tried running the new version of vodrecovery and it will just instantly close as soon as I run it. I did URL cloning through the github URL and still, it will not run.

**Comment by ItIckeYd** [comment]
@lol1337123123 I believe this is due to using grerequests.. you may have to download an actual ide such as pycharm or visual studio code.

I would have to make an actual executable to make it runnable on its own.

**Comment by ItIckeYd** [comment]
@lol1337123123 I made a few configuration changes. You should be able to run the script directly again... apologies for the inconvenience. 

Closing this issue as not relevant anymore.
