### ISSUE TITLE
just updated getting this error

### ISSUE THREAD

**Issue by youngkiller1988** [ItIckeYd/VodRecovery#44]
![Sc](https://user-images.githubusercontent.com/82237017/172501620-9e55c30d-35dd-4cde-9a1d-2c1deeb00b72.png)
only showed up after i updated the script

**Comment by youngkiller1988** [comment]
never mind didn't realize grequests were a different thing from request installed and now seems to be working again

**Comment by ItIckeYd** [comment]
@youngkiller1988 can you specify what you mean by updating the script?
