### ISSUE TITLE
Hello, I need some help. (Crosspost from TwitchRecovery, apologies, don't know which one you check more!)

### ISSUE THREAD

**Issue by Nicejankyname** [ItIckeYd/VodRecovery#46]
Hello. First of all, thank you for the work on this project. I spent all night putting together how to run Python and make sure all of the features work. I finally, at 5:36 AM EST time, managed to get the thing to work. Hooray! Now I have this problem.

Please choose an option: 1
Enter streamer name: Airwalker7
Enter vod id: https://twitchtracker.com/airwalker7/streams/39492915528
Enter VOD timestamp (YYYY-MM-DD HH:MM:SS): 2022-06-07 10:08:00
Vod is 0 days old. If the vod is older than 60 days chances of recovery are slim.

No vods found using current domain list.

On that particular example I used the time that was given to me by twitchtracker.com I understand that I am supposed to convert things to my timezone, but unless the late night is getting to me, I can't seem to figure out what that could possibly be. I have tried -4 hours, -5 hours, and even used a Google converter to confirm that I'm not insane. I have also tried to bring up other videos in case that one is deleted or something, including a video that is currently on Twitch itself. So.... please help me?

**Comment by ItIckeYd** [comment]
@Nicejankyname 

https://dgeft87wbj63p.cloudfront.net/35b1123d9c7a9da8406e_airwalker7_39492915528_1654610924/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
Total Number of Segments: 530
Would you like to check if segments are valid (Y/N): y
530 of 530 segments are valid.

TwitchTracker will automatically set a timezone when you visit the site. Please tell me what that timezone is.. it should be on the top right beside the "Sign In" button. If the timezone is set to something other then UTC then that is probably your issue. If it is set to UTC please tell me where you live a state/province please do not provide any revealing details.

**Comment by Nicejankyname** [comment]
Thank you for the reply. I am glad to see I am doing something wrong and the link works, thank you for that. This is a learning moment to me. I am in the Northeastern part of the USA. I use the Eastern timezone, so UTC-4 because of daylight savings time now. That would put the video at 6:08:00 my time, but trying that gets me the result I posted above. What am I missing here?

**Comment by ItIckeYd** [comment]
@Nicejankyname
Enter vod id: https://twitchtracker.com/airwalker7/streams/39492915528

its not asking for the link.. please only provide the ID as requested.

**Comment by Nicejankyname** [comment]
Hmm. Still same result. Can you copy and paste exactly what you put into the answer boxes so I can see if I'm formatting something incorrectly please?

**Comment by ItIckeYd** [comment]
@Nicejankyname Try the exact same thing only use UTC-5 instead. The only timezones in EST are -4/-5

**Comment by ItIckeYd** [comment]
Please choose an option: 1
Enter streamer name: Airwalker7
Enter vod id: 39492915528
Enter VOD timestamp (YYYY-MM-DD HH:MM:SS): 2022-06-07 11:08:00

Im UTC-3

**Comment by Nicejankyname** [comment]
Still the same result. I... don't understand. The timezone on the top right is UTC. I can switch it to UTC-4 though, but I have it at UTC.

**Comment by ItIckeYd** [comment]
@Nicejankyname Switch it to UTC-4 and use the time it has set when switched. It should work as it is setting it to your timezone.

**Comment by Nicejankyname** [comment]
Oh boy... Please choose an option: 1
Enter streamer name: Airwalker7
Enter vod id: 39492915528
Enter VOD timestamp (YYYY-MM-DD HH:MM:SS): 2022-06-07 10:08:00
Vod is 0 days old. If the vod is older than 60 days chances of recovery are slim.

No vods found using current domain list.

WELCOME TO VOD RECOVERY

1) Recover Vod
2) Recover Clips
3) Exit

Please choose an option:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in run_script
ValueError: invalid literal for int() with base 10: ''

**Comment by ItIckeYd** [comment]
@Nicejankyname Airwalker7 vs airwalker7 are different words please use the one listed on twitchtracker which would be airwalker7

**Comment by Nicejankyname** [comment]
FFS. It was because I used "Airwalker" instead of "airwalker". I was trying to be as accurate as I could with the information I was relaying to the program. Hahahaha! Whew. Thank you for your help! I'm going to learn Python now, this coding language seems very easy to overthink, which means it may be a fun challenge as I tend to overthink things a lot. Thanks again!!

**Comment by ItIckeYd** [comment]
@Nicejankyname That is a bug.. in the program I will fix and have created an issue for it.

**Comment by Nicejankyname** [comment]
Thank you for this. This streamer has stopped publishing VODS and I like to keep up with him, so it will be cool to be able to see his videos again every day. :)
