### ISSUE TITLE
Downloading sub-only VOD

### ISSUE THREAD

**Issue by 3N4N** [ItIckeYd/VodRecovery#49]
I haven't been able to retrieve [this vod](https://www.twitch.tv/videos/1305904244) with your python script. I don't know how to get the timestamp.

Also, I saw that you're active in the [TwitchRecover](https://github.com/TwitchRecover/TwitchRecover) project. I have [forked that](https://github.com/3N4N/TwitchRecover) quite some time ago and fixed some regexp related bugs (then rewrote most of the program to suite my needs) and it worked excellently. Or it used to. Today, after a long time, I tried to retrieve [this sub-only vod](https://www.twitch.tv/videos/1305904244) and it doesn't work. My guess is that the client-id used in the program has been deactivated or something. Any idea?

**Comment by ItIckeYd** [comment]
@3N4N For my script you have to use twitchtracker/sullygnome/streamscharts.. Please read the README located in homepage of repository before running script for full details.

**Comment by 3N4N** [comment]
I read your README. It only lists those three websites. Doesn't explain what timestamp means or how to get it from those websites.

And what do you mean by "vod only clips"? The description in this repo says "Python script created to retrieve **sub only**/deleted videos/clips from twitch."

**Comment by ItIckeYd** [comment]
@3N4N timestamp is the datetime which the vod started and can be found on any of those websites (note must be converted to your timezone).

downloading and retrieving vods are completely different things. Retrieving meaning providing the link to the vod and downloading means actually downloading the vod like you would a youtube video. my script does not contain functionality to download vods as I stated... only download clips.

**Comment by 3N4N** [comment]
Okay, I misspoke. I want to "retrieve" the VOD link. And that VOD I linked in the OP doesn't show up in those three websites. So they must be un-retrievable.

Closing.
