### ISSUE TITLE
Doesn’t work for deleted vod

### ISSUE THREAD

**Issue by lbbl03** [ItIckeYd/VodRecovery#5]
So I just spent some time trying it out and I found that this works great for sub-only vods that are still available on twitch. I just had to match the time to UTC-3 and it worked for mutiple vods.

When I tried it with a vod that was deleted by the streamer this morning it didn’t find any files.

I heard that twitch has changed the way they handle deleted vods and will now delete the files from their server immediately, is that true?

**Comment by ItIckeYd** [comment]
@lbbl03 Yes, the script is limited to twitch's current deletion process. In some cases vods are recoverable up to 60 days and in others.. vods are deleted the minute the streamer goes offline. If you are unable to recover a vod it just means it was removed by twitch.
