### ISSUE TITLE
Interesting situation where I can't find any of my VODs

### ISSUE THREAD

**Issue by cdtharp** [ItIckeYd/VodRecovery#50]
Recently amazon decided to randomly not allow my prime gaming payment to go through, and as a result all of my VODs older than 2 weeks have disappeared from my video manager. I contacted twitch support and they were pretty useless, wouldn't read my ticket like 3 times and when they finally understood what the issue was they shrugged their shoulders and said we can't help you.

When I tried using your program to recover them (wonderful script by the way, much better than the other ones out there that exist) none of VODs older than 2 weeks would show up. I'm really sad as that's nearly 2 months of streams gone, along with some of the best memories of my life from a trip I went on. I've started to accept that I've been fucked over by amazon and if that's the case then that's okay. 

I wanted to reach out and put in a ticket at least in case this unique situation interests you and if you think there's any way for me to retrieve these VODs. 
My twitch channel is tharpy_ in case you end up needing to look anything up on the analytical sites.

**Comment by ItIckeYd** [comment]
@cdtharp If you inputted everything correctly and the script returned 0 results then i'm afraid the vods just don't exist anymore.  I don't currently have any other methods of retrieval.
