### ISSUE TITLE
Script can't pass through cloudfare

### ISSUE THREAD

**Issue by DySt4f** [ItIckeYd/VodRecovery#51]
As the tittle says I think twitchtracker updated the protection to access the website since this week the site have been slowly working

Today as I was trying using the script in the morning it works fine, but then at night it just stop working, I enter twitchtracker and noticed the cloudfare protection message pop when it doesn't used to, so I just imagine now the script need an implementation to pass through it, I know there are some packages in python to properly resolve this but I don't really know how to implement them across this script

I'll gladly appreciate it if can help us with it, thanks for the good work

**Comment by ItIckeYd** [comment]
@DySt4f i don't make any calls to the twitchtracker site. I don't scrape the site or make HTTP requests to retrieve information from the site... therefore I can't see this being the issue you are experiencing.

**Comment by DySt4f** [comment]
@ItIckeYd, I though the script scrape over twitchtracker somehow but really didn't think about it clearly, I messed the domain urls format when trying to recover a vod as soon as the stream was over just because it didn't appear on the servers, however I have fixed it and now its working again.

Thanks for the fast response and I apologize because you're right I need to ask this in the right github.
