### ISSUE TITLE
Missing segments

### ISSUE THREAD

**Issue by DySt4f** [ItIckeYd/VodRecovery#55]
Hello! I've seen sometimes a VOD is shorter than expected, for example: if you try to recover [this one](https://twitchtracker.com/koo_emong/streams/39442470279) it says it's complete with only a number of 93 valid segments, when it should be longer since that's only 15 mins compared to the 5,5 hours that lasted.

Is there any way to recover this VOD or any VOD that got this problem? I've seen this happen more times than I'd like, however I haven't found a solution.

Thanks in advance!

**Comment by blackesteagle** [comment]
check streamscharts site and you'll see more links for that vod and use their IDs, this happens often if streams has disconnects, currently only streamscharts lists the missing parts.
