### ISSUE TITLE
Can you detect the VOD timestamp automatically?

### ISSUE THREAD

**Issue by ellipticaldoor** [ItIckeYd/VodRecovery#56]
It's quite annoying to have to find the time manually depending on your local time, could be possible to just make it automatic?

**Comment by ItIckeYd** [comment]
@ellipticaldoor to find the time you just have to browse to one of the three sites.. twitchtracker, sullygnome or streamscharts. I can't see it being annoying because in order to get the vod id you need to be on those sites anyway.

**Comment by ellipticaldoor** [comment]
Can you check if I'm doint it properly? I'm not sure if I'm putting the date wrong

```
python3 RecoverVod.py
WELCOME TO VOD RECOVERY

1) Recover Vod
2) Recover Clips
3) Unmute an M3U8 file
4) Check M3U8 Segments
5) Exit

Please choose an option: 1
Enter streamer name: j_blow
Enter vod id: https://twitchtracker.com/j_blow/streams/39859591657
Enter VOD timestamp (YYYY-MM-DD HH:MM:SS): 2022-07-03 02:06:00
Vod is 0 days old. If the vod is older than 60 days chances of recovery are slim.

No vods found using current domain list.
```

**Comment by ItIckeYd** [comment]
@ellipticaldoor I don't know your timezone so I wouldn't know if this is correct however the format of the datetime is correct... as stated in the program YYYY-MM-DD HH:MM:SS.

**Comment by ItIckeYd** [comment]
Results of the vod you were trying to recover..

https://d2vjef5jvl6bfs.cloudfront.net/5a420c10281256199e2f_j_blow_39859591657_1656810396/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
Total Number of Segments: 121
3 of 121 segments are valid.

Given there is only 3 segments available.. the vod would not be playable.

**Comment by ellipticaldoor** [comment]
oh I see thanks

**Comment by ItIckeYd** [comment]
@ellipticaldoor you only need the vod id... please not use the full link as that will never return results..?

Enter vod id: https://twitchtracker.com/j_blow/streams/39859591657 WRONG
Enter vod id: 39859591657 CORRECT

**Comment by ellipticaldoor** [comment]
so this stream is not possible to recover right?

**Comment by ItIckeYd** [comment]
@ellipticaldoor about 1 minute would be playable probably less.. also no indication as to which minute. You would have to find it.

**Comment by ItIckeYd** [comment]
#67
