### ISSUE TITLE
Unable to download any Vod.

### ISSUE THREAD

**Issue by Inamaru** [ItIckeYd/VodRecovery#57]
Hi, sorry to bother, 

But as the title says, I'm having issues using your scripts. Note that I'm not an expert so probably I'm missing something.
whatever kind of vod I'm trying to download. (New/old ones, sub and not sub only) i keep getting the same error. "No vods founds using the current domain".

I installed the required packages (on requirements.txt) and tried to use the script both on cmd and visual studio code. 
Both give me the same problem.

I wanted to use the script for downloading a sub only vod. After few tries I was wondering if maybe it was only bad luck but it seems that I'm unable to download any type of vod at all.

So I tried to download a vod as a test from this streamer:

PS: On twitchleecher I'm able to download this vod without troubles at all.

https://twitchtracker.com/sergiocalvominiatures/streams/39575445384

https://puu.sh/J9zbj/aee1188143.png

Clearly there are some missing step that I'm unaware (or probably without realizing I missed.)
Thanks for your time and sorry for the trouble.

**Comment by ItIckeYd** [comment]
@Inamaru my script does not contain functionality to download a vod. It only has the ability to retrieve an m3u8 file which will expire in time up to 60 days from when the vod was originally broadcast. 

If the script is not working. Most likely you are not using the correct timezone. Please figure out the correct timezone and apply the offset as required when running the script.

Example: 

My timezone is UTC-3 so I would subtract 3 hours from whatever the UTC timestamp is on one of the three sites that are stated in the README file. 

If the timezone information is correct and you are still receiving the same message please try other vods from within the 60 day timeframe.
