### ISSUE TITLE
Vod recover error

### ISSUE THREAD

**Issue by xDalLio** [ItIckeYd/VodRecovery#58]
Hi, I'm trying to recover this vod using your tool: https://twitchtracker.com/sabaku_no_sutoriimaa/streams/39580566952 (it is from 8 days ago). 
After inserting the timestamp i get this error: "No vods found using current domain list.".
The timestamp i used doesn't have seconds (i can't manage to find where seconds are in the sites you linked in the readme) (i.e.  2022-06-29 19:35:00). I'm using UTC +0, is it correct?

Thank you so much.

**Comment by ItIckeYd** [comment]
@xDalLio You have to use your local timezone as stated in README.

Example:

My time zone is UTC-3.

So given twitchtracker states Wed, Jun 29, 19:34 is the start time as UTC-0 

I would input the following into the script.. Wed, Jun 29, 16:34

**Comment by ItIckeYd** [comment]
Closing issue as no further discussion.
