### ISSUE TITLE
Having trouble recovering a vod

### ISSUE THREAD

**Issue by wishingtile** [ItIckeYd/VodRecovery#59]
Hopefully someone can help me understand what im doing wrong here.

Twitch link for vod I want recovered (not sure if this matters) https://www.twitch.tv/videos/1525611219

Stream charts link for the vod (cant find it on other sites for some reason) https://streamscharts.com/channels/djjeckel65/streams/40957749131

This is how im entering it in to python:

Please choose an option: 1
Enter streamer name: djjeckel65
Enter vod id: 40957749131
Enter VOD timestamp (YYYY-MM-DD HH:MM:SS): 2022-07-07 23:45:00
Vod is 0 days old. If the vod is older than 60 days chances of recovery are slim.

No vods found using current domain list.

I believe im doing everything right. The timestamp listed on streamcharts says 03:45, converted to my local time it would be 23:45 (assuming im supposed to use 24 hour time?)

Anyone have any ideas on what I could be doing wrong here?

**Comment by ItIckeYd** [comment]
@wishingtile You not inputting the correct start time on StreamsCharts it indicates the following as the start time:  08 Jul 2022, 03:30... i'm not sure where you got 3:45 from.

**Comment by wishingtile** [comment]
@ItIckeYd 
Wow. Im blown back by your quick reply. Thank you so much. I neglected to mention that I saw 2 times on there, the 03:30 on top and the 03:45 on towards the bottom on the right of the page. Not sure why, but ive tried them both with the same result. Anything else I could be missing?

**Comment by ItIckeYd** [comment]
@wishingtile Vod most likely just doesn't exist anymore. I tried it myself got the same results.

**Comment by wishingtile** [comment]
@ItIckeYd Ah ok. Well thanks for checking and responding. Glad to know that im doing everything right. Awesome program! 

Can I gift you a steam game or something?

**Comment by ItIckeYd** [comment]
@wishingtile No, I do not accept any type of donations or gifts.

**Comment by wishingtile** [comment]
@ItIckeYd Ok, just thought I would offer. Youre amazing for doing all of this for free! Keep being great dude!
