### ISSUE TITLE
WinError 10055 problem happened. how to fix it?

### ISSUE THREAD

**Issue by qa159123** [ItIckeYd/VodRecovery#62]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='vod-metro.twitch.tv', port=443): Max retries exceeded with url: /023b8f133545fb8cbbd1_winter_28270_39489925943_1657888921/chunked/index-dvr.m3u8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022846AC05E0>: Failed to establish a new connection: [WinError 10055]

**Comment by ItIckeYd** [comment]
Issue is a few months old and I believe issue has been fixed with the implementation of grequests and sessions..

closing issue now.
