### ISSUE TITLE
incomplete vod link?

### ISSUE THREAD

**Issue by ffedericode** [ItIckeYd/VodRecovery#63]
Hi, i'm trying to recover this VOD 
https://twitchtracker.com/ritaglitch/streams/39634497192
and I noticed that it's just a 200 segments m3u8 file (approx 45 mins video) of a 12 hours stream. it never happened to me with other channels, even when 12+ hours video. i noticed that only on her channel and in at least two different vods. there're no muted parts!

let me know if there's a solution or another link to get the whole vod! Thank you so much.

**Comment by ItIckeYd** [comment]
Check StreamsCharts.. vod might have been separated into multiple vods meaning multiple vod id's.

**Comment by ffedericode** [comment]
it works! i love you dude, thank you so much.
