### ISSUE TITLE
unable to find the vod 

### ISSUE THREAD

**Issue by haz-d05** [ItIckeYd/VodRecovery#64]
i have tried everything 

Please choose an option: 1
Enter streamer name: trasdaa
Enter vod id: https://streamscharts.com/channels/trasdaa/streams/41016817707
Enter VOD timestamp (YYYY-MM-DD HH:MM:SS): 2022-07-21 06:55:00
Vod is 0 days old. If the vod is older than 60 days chances of recovery are slim.

the timestamp that was posted on streamcharts said 6:55 pm but as I use GMT timezone (British) I have no clue how to convert to my time to find the vod
the date is right, so is everything else, but the time I just cannot figure out.
wondering if anybody more experienced could try and find the vod for me or help in any way

Much Appreciated :}

**Comment by ItIckeYd** [comment]
@haz-d05 do not enter full link as vod id... only enter the actual vod id.

**Comment by haz-d05** [comment]
> @haz-d05 do not enter full link as vod id... only enter the actual vod id.

i tried before doing the only the id and it said the same thing ,is there any way you could try and recover the vod as your much more experienced than me lol I wish I knew how

**Comment by ItIckeYd** [comment]
@haz-d05 I tried the vod id you stated however I got the same results as you therefore the vod probably just doesn't exist.

I looked at twitchtracker for the same date and got the following:
https://ds0h3roq6wcgc.cloudfront.net/e9e98d1dc1f3638c4b8e_trasdaa_41016964571_1658433166/chunked/index-dvr.m3u8

**Comment by haz-d05** [comment]
> @haz-d05 I tried the vod id you stated however I got the same results as you therefore the vod probably just doesn't exist.
> 
> I looked at twitchtracker for the same date and got the following: https://ds0h3roq6wcgc.cloudfront.net/e9e98d1dc1f3638c4b8e_trasdaa_41016964571_1658433166/chunked/index-dvr.m3u8

hmm, strange. he deleted the vod and then started a new stream right after. I believe the vod pops up on streamcharts and was around 40 minutes, the streamer was doubting that I couldn’t get the vod back so I really wanted to prove him wrong by using this method but if we can’t do it then it’s fine I guess
