### ISSUE TITLE
Option to select clip url format for all vods

### ISSUE THREAD

**Issue by GuardToad** [ItIckeYd/VodRecovery#70]
it's a bit tedious to select the format for every vod, something similar to the "Do you want to download the recovered clips (Y/N" option would be nice so u can just have it running in the background.

**Comment by ItIckeYd** [comment]
@GuardToad Whoops, never realized. this will be implemented in the next day or two.

**Comment by blackesteagle** [comment]
Yep, asking anything during recovery for each stream definitely defeats most of bulk recovery's purpose :P 

How about an additional option for combined recovery, where the program makes 3 passes for each stream; checks for all 3 possible formats consecutively?

**Comment by ItIckeYd** [comment]
@blackesteagle that can be done as well. The only downfall with it is the amount of urls the script will have to check... but I will implement as requested.

**Comment by blackesteagle** [comment]
I've scanned over a 100 vods from 2017 with option 2 and once again with 3 today, didn't recover a single clip yet. Now I'm not sure if it'd be worth to extend the time to check a vod by 3x if these options are very unlikely to find clips :/ I'll check more vods from other years/diff streamers this week.

**Comment by ItIckeYd** [comment]
@blackesteagle Its mainly a guess as to which option to use... I would almost in all cases use the default format first to see if it finds a clip after 20% of the total count if not then move on to the other formats.  I would also take in to account how popular the vods you are trying were... if the concurrent viewership < 300 I wouldn't bet on many clips being found in any of the formats.

**Comment by ItIckeYd** [comment]
@blackesteagle  @GuardToad Script now allows the user to select whatever formats they would like in any order 1 through 3 and only prompts user once.

formats selected will automatically be appended to the result set.
