### ISSUE TITLE
Clip Recovery Possible Improvement

### ISSUE THREAD

**Issue by ambhaiji** [ItIckeYd/VodRecovery#71]
After doing some basic research based on a number of clips I already had in my personal archive, 
Based on a stream from 2017 where I recovered clips from both Option 1&3 and,
A small test I did just recently suggests that the Clip Recovery Option no,3 aka Alternate might only be clips created after the stream is moved to the archive and the ID it bears within the filename is that of the `video_id` usually found as `twitch.tv/videos/<video_id>` instead of using the `stream_id` which seems to be clips created while live.

My small test was done using a shroud's stream from yesterday where I created a clip today from the archive
[https://clips-media-assets2.twitch.tv/vod-1574370130-offset-15848.mp4](https://clips-media-assets2.twitch.tv/vod-1574370130-offset-15848.mp4) and,
got this clip I know was made while he was live based of the time from Twitch Tracker
[https://clips-media-assets2.twitch.tv/41180025483-offset-15222.mp4](https://clips-media-assets2.twitch.tv/41180025483-offset-15222.mp4)

Here is a Twitch API Request to verify all of this
```
twitch api get videos -q id=1574370130
{
  "data": [
    {
      "created_at": "2022-08-27T19:35:44Z",
      "description": "",
      "duration": "8h57m30s",
      "id": "1574370130",
      "language": "en",
      "muted_segments": null,
      "published_at": "2022-08-27T19:35:44Z",
      "stream_id": "41180025483",
      "thumbnail_url": "https://static-cdn.jtvnw.net/cf_vods/d2nvs31859zcd8/24947ae81e2d72634fd8_shroud_41180025483_1661628939//thumb/thumb0-%{width}x%{height}.jpg",
      "title": "I lied, duos with tarik",
      "type": "archive",
      "url": "https://www.twitch.tv/videos/1574370130",
      "user_id": "37402112",
      "user_login": "shroud",
      "user_name": "shroud",
      "view_count": 797643,
      "viewable": "public"
    }
  ],
  "pagination": {
    "cursor": ""
  }
}
```

**Comment by ItIckeYd** [comment]
@ambhaiji good analysis and conclusion. I am unsure as to what change is being suggested to the script? The issue with the conclusion is that without interacting with Twitch API there is no way to know what vod's are considered 'type: archive' as vods that do not currently exist on twitch servers still use the default clip url format (https://clips-media-assets2.twitch.tv/41180025483-offset-15222.mp4).  I think unless I pulled information from Twitch API and implemented more conditionals based on the information that the Twitch API presents.. it is mostly a guess as to which clip format is used for which vods.

**Comment by ambhaiji** [comment]
> I am unsure as to what change is being suggested to the script?
as of now not sure because I am still researching into this.

but what I meant to prove is that a stream does not only have one type of clip but actually 3
1. `stream_id` -offset- i .mp4 (clips made while the stream was running live)
2. vod- `video_id` -offset- i.mp4 (clips made for the same stream after it went offline)
3. `AT-cm_` 9 digit numeric/22 character Alphanumeric including( - )( _ ) (non 30s custom clips live or non-live)

Twitch Tracker seems to be able to look for these AT-cm_ clips but I am assuming they are doing so using Twitch API.

**Comment by ambhaiji** [comment]
the problem now is that none of the tracking websites have the `video_id` recorded or have not made it visible to us browsing their site.

**Comment by ambhaiji** [comment]
12-Aug-2016
[https://blog.twitch.tv/en/2016/08/12/all-your-clips-in-a-single-spot-187ea5d135c/](https://blog.twitch.tv/en/2016/08/12/all-your-clips-in-a-single-spot-187ea5d135c/)

this seems to be the day they started using `-offset-` instead of the `-index-` filenames, but there are some overlapping streams at different dates for different streamers.


26-May-2016
[https://blog.twitch.tv/en/2016/05/26/announcing-clips-f8ade2113ddf/](https://blog.twitch.tv/en/2016/05/26/announcing-clips-f8ade2113ddf/)

This is when clipping was born so people shouldn't really bother to find clips before this, atleast using Option 1 or 2
and if they use Option 3 to use the `video_id` instead

For the sake of making sure this information is correct everyone using this script should try both Options 1 and 2 for all of August 2016 and report their findings.

**Comment by ItIckeYd** [comment]
@ambhaiji There is major overlap between -offset- and -index- basically right to the end of August.

**Comment by ItIckeYd** [comment]
#70 Marking as related

**Comment by ambhaiji** [comment]
oh I completely forgot about the part where the clips that use `-index-` have odd number clips as well and is not even exclusive

**Comment by ambhaiji** [comment]
I checked out the new changes but believe it would be cleaner to use YYYYMMDD and have more detailed information here
1) Default (20160801 - Present)  '-offset-' clips
2) Alternate (Any VOD) Clips starting with 'vod-'
3) Legacy (20160525-20160831) Old -index- style clips

The hints will be useful going forward since option 2 and 3 swapped places.
I was able to get clips from 2013 using `vod-` aka new Option 2 and also I can just make new clips with that namestyle from any available past broadcast.
I am very sure now that `vod-` is clips made from completed streams only as it is the only type of clips available before 26 May 2016. 
20160525 instead of 20150526 because timezones.

**Comment by blackesteagle** [comment]
> This is when clipping was born so people shouldn't really bother to find clips before this, atleast using Option 1 or 2
> and if they use Option 3 to use the `video_id` instead

So option 3 is useless without the "video_id"s? And IDs at the tracker sites are stream IDs and not video IDs and everybody keeps mentioning video IDs but no one knows how to get them right? Or am I wrong about any of this?

**Comment by ambhaiji** [comment]
> > This is when clipping was born so people shouldn't really bother to find clips before this, atleast using Option 1 or 2
> > and if they use Option 3 to use the `video_id` instead
> 
> So option 3 is useless without the "video_id"s? And IDs at the tracker sites are stream IDs and not video IDs and everybody keeps mentioning video IDs but no one knows how to get them right? Or am I wrong about any of this?

Please note Option 2 and 3 swapped places since I said that in the newer master releases. and for the long run that makes sense because the new Option 2 has a lot more clips than the one that lasted about 3 months.

`video_id` is easily available for VODs that still are public because you just get them at the end of the twitch URL but for anything that was pre DMCA purge or was just removed for other reasons is for now not possible easily. The only hope is the tracking websites actually have similar json data to the top post cached within their servers and can make a change to have those links available for us to see.

**Comment by ItIckeYd** [comment]
Marking this as completed as script now offers 3 clip formats all of which are available to the user all at once or in whatever combination they choose.

Closing this now.
