### ISSUE TITLE
Software Language Improvement Request

### ISSUE THREAD

**Issue by ambhaiji** [ItIckeYd/VodRecovery#72]
This is mostly a major derp moment on my part but if possible I'm sure someone has or will also face this issue and if somehow can be more clear would be greatly appreciated.
Because the full VOD recovery requires the original time of the creation of the VOD I assumed the same for Clip Recovery but I eventually realized it wants me to input the duration of the VOD instead for Clip Recovery.

My suggestion is to have it like so

Enter stream duration hour value:
Enter stream duration minute value:

**Comment by ItIckeYd** [comment]
@ambhaiji Change will be implemented in the next commit.

**Comment by ItIckeYd** [comment]
@ambhaiji 

This has been implemented along with some other wording changes.

**Comment by ambhaiji** [comment]
Awesome thanks
