### ISSUE TITLE
ModuleNotFoundError: No module named 'grequests'

### ISSUE THREAD

**Issue by JoePatty711** [ItIckeYd/VodRecovery#74]
Sorry for possibly dumb question, I am new to this. 
I was running an older version of this script just fine, but went to the most updated version and am getting this error upon running it now: 

_ModuleNotFoundError: No module named 'grequests'_

Any tips for fixing this? Thanks

**Comment by ItIckeYd** [comment]
@JoePatty711 you need to install the grequests package via pip or by running the requirements.txt file available in my repository.
