### ISSUE TITLE
Bulk recover clips

### ISSUE THREAD

**Issue by ujrarozu** [ItIckeYd/VodRecovery#76]
Hello i have a problem bulk recovering clips wont work but i dont know why, it crashes for me and if i run it trough powershell i can see the error it says : 

Traceback (most recent call last):
  File "G:\Rtrecover\NEU\NEU 27-06\VodRecovery-1.0.0.9\RecoverVod.py", line 420, in <module>
    run_script()
  File "G:\Rtrecover\NEU\NEU 27-06\VodRecovery-1.0.0.9\RecoverVod.py", line 402, in run_script
    bulk_clip_recovery()
  File "G:\Rtrecover\NEU\NEU 27-06\VodRecovery-1.0.0.9\RecoverVod.py", line 334, in bulk_clip_recovery
    for vod, duration in parse_csv_file(file_path).items():
  File "G:\Rtrecover\NEU\NEU 27-06\VodRecovery-1.0.0.9\RecoverVod.py", line 294, in parse_csv_file
    csv_file = open(file_path, "r+")
PermissionError: [Errno 13] Permission denied: 'G:\\Rtrecover\\NEU\\NEU 27-06\\VodRecovery-1.0.0.9'

-----------------------------------------------------------------------------------------------------------------------------

**on my second try i gave the program the exact path with the csv file name so :** 

G:\Rtrecover\NEU\NEU 27-06\VodRecovery-1.0.0.9\xxtretertert.csv
Traceback (most recent call last):
  File "G:\Rtrecover\NEU\NEU 27-06\VodRecovery-1.0.0.9\RecoverVod.py", line 420, in <module>
    run_script()
  File "G:\Rtrecover\NEU\NEU 27-06\VodRecovery-1.0.0.9\RecoverVod.py", line 402, in run_script
    bulk_clip_recovery()
  File "G:\Rtrecover\NEU\NEU 27-06\VodRecovery-1.0.0.9\RecoverVod.py", line 334, in bulk_clip_recovery
    for vod, duration in parse_csv_file(file_path).items():
  File "G:\Rtrecover\NEU\NEU 27-06\VodRecovery-1.0.0.9\RecoverVod.py", line 300, in parse_csv_file
    reps = ((int(final_string[1].strip()) * 60) + 2000) * 2
ValueError: invalid literal for int() with base 10: '"504"'

can anyone help me or link his discord so we can chat better ?, i also tried running the python trough python idle with run module and also trough powershell

**Comment by ujrarozu** [comment]
> @ujrarozu Can you provide an example of what was entered when the script was run?

yes of course, can i contact u somewhere maybe we can chat faster than if u want, i tried bulk recover clips i wrote the streamer name and than i write the path to the csv file like this : G:\Rtrecover\NEU\NEU 27-06\VodRecovery-1.0.0.9\xxtretertert.csv

**Comment by ItIckeYd** [comment]
@ujrarozu download the latest code from main branch in repository.

**Comment by ujrarozu** [comment]
@ItIckeYd thank you its fixed now but is it normal that the program is very slow ? after pasting the path of my csv file i press download all clips Y , than i use default and it begins going trough the vods and it goes like this 500 of 32240 , and every 5 seconds it adds up 500 more its very slow

**Comment by ujrarozu** [comment]
i have wfuzz installed is the bulk recover not using wfuzz or why is it that slow ?

**Comment by ItIckeYd** [comment]
@ujrarozu my script does not use wfuzz. The script uses grequests which is module that allows for asynchronous requests.

**Comment by ujrarozu** [comment]
@ItIckeYd new problem after the program finishes loading and going trough every vod it just restarts the program and nothing happens the clips wont download or something 
![image](https://user-images.githubusercontent.com/103399281/191369310-d041c225-dd77-4caf-9a20-fca3d0a0803b.png)

**Comment by ItIckeYd** [comment]
@ujrarozu  Not an issue just no clips were found for the vod that was being questioned.

**Comment by ItIckeYd** [comment]
Issue resolved... closing now.
