### ISSUE TITLE
where do i go from here ?

### ISSUE THREAD

**Issue by tlalter** [ItIckeYd/VodRecovery#78]
ModuleNotFoundError: No module named 'grequests'

I got lost navigating directory and after installing packages . Help is appreciated

**Comment by ItIckeYd** [comment]
@tlalter You need to install grequests module using pip.

To achieve this you can look at the various tutorials on youtube.... "How to install python modules".

**Comment by ItIckeYd** [comment]
Closing... no further discussion.
