### ISSUE TITLE
Download/Convert M3u8 to Mp4

### ISSUE THREAD

**Issue by ItIckeYd** [ItIckeYd/VodRecovery#8]
Allow users to download/convert m3u8 to mp4.

**Comment by Maxiskw** [comment]
how do you convert m3u8 to mp4 ?

**Comment by inthemostwantedsea** [comment]
if you don't know how to download m3u8 or convert m3u8 into mp4, try streamfab downloader! a perfect m3u8 downloader I've used. Its function is strong and comprehensive. read this article, I hope it will provide some help. https://www.dvdfab.cn/resource/video/m3u8-downloader

**Comment by ItIckeYd** [comment]
Download functionality is now supported for M3U8's.. Closing issue.
