### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jakethewake** [ItIckeYd/VodRecovery#80]
On the latest version if the script i get this error "FileNotFoundError: [Errno 2] No such file or directory" posted the logs below.

64 Clip(s) Found                                                                                                       
Do you want to log results to file (Y/N): y                                                                             
Traceback (most recent call last):                                                                                        
File "/app/1.py", line 611, in <module>                                                                                   
run_script()                                                                                                          
File "/app/1.py", line 587, in run_script                                                                                 
recover_all_clips()                                                                                                   
File "/app/1.py", line 403, in recover_all_clips                                                                          
with open(generate_log_filename(streamer, vod_id), "w") as log_file:                                                
FileNotFoundError: [Errno 2] No such file or directory: '~\\Documents\\/loltyler1_47302704813_log.txt'

**Comment by ItIckeYd** [comment]
@jakethewake When you input the streamer name did you also input a forward slash? "/loltyler1"

**Comment by jakethewake** [comment]
no, i only put "loltyler1"

**Comment by ItIckeYd** [comment]
@jakethewake i tried the same one and it worked fine for me the path in the error suggests a forward was input at the start of the streamer name '~\Documents\/loltyler1_47302704813_log.txt'

**Comment by ItIckeYd** [comment]
No further discussion... closing issue.

**Comment by jakethewake** [comment]
this is the whole log

WELCOME TO VOD RECOVERY

1) Recover Vod
2) Recover Clips
3) Unmute an M3U8 file
4) Check M3U8 Segments
5) Download M3U8 (.MP4 extension)
6) Exit

Please choose an option: 2
Enter what type of clip recovery:
1) Recover all clips from a single VOD
2) Find random clips from a single VOD
3) Bulk recover clips from SullyGnome CSV export
1
Enter streamer name: loltyler1
Enter vod id: 47302704813
Enter stream duration hour value: 0
Enter stream duration minute value: 1
What clip url format would you like to use (IF multiple.. separate by spaces)?
1) Default (Most vods)
2) Alternate (2017 and up)
3) Archived (June-August of 2016)
1
1 Clip(s) Found
2 Clip(s) Found
3 Clip(s) Found
4 Clip(s) Found
5 Clip(s) Found
6 Clip(s) Found
7 Clip(s) Found
8 Clip(s) Found
9 Clip(s) Found
10 Clip(s) Found
11 Clip(s) Found
12 Clip(s) Found
13 Clip(s) Found
14 Clip(s) Found
15 Clip(s) Found
16 Clip(s) Found
17 Clip(s) Found
18 Clip(s) Found
19 Clip(s) Found
20 Clip(s) Found
21 Clip(s) Found
22 Clip(s) Found
23 Clip(s) Found
24 Clip(s) Found
25 Clip(s) Found
26 Clip(s) Found
27 Clip(s) Found
28 Clip(s) Found
500 of 1030
29 Clip(s) Found
30 Clip(s) Found
31 Clip(s) Found
32 Clip(s) Found
33 Clip(s) Found
34 Clip(s) Found
35 Clip(s) Found
36 Clip(s) Found
37 Clip(s) Found
38 Clip(s) Found
39 Clip(s) Found
40 Clip(s) Found
41 Clip(s) Found
42 Clip(s) Found
43 Clip(s) Found
44 Clip(s) Found
45 Clip(s) Found
46 Clip(s) Found
47 Clip(s) Found
48 Clip(s) Found
49 Clip(s) Found
50 Clip(s) Found
51 Clip(s) Found
52 Clip(s) Found
53 Clip(s) Found
54 Clip(s) Found
55 Clip(s) Found
56 Clip(s) Found
57 Clip(s) Found
58 Clip(s) Found
59 Clip(s) Found
60 Clip(s) Found
61 Clip(s) Found
62 Clip(s) Found
63 Clip(s) Found
64 Clip(s) Found
1000 of 1030
Do you want to log results to file (Y/N): y
Traceback (most recent call last):
  File "RecoverVod.py", line 611, in <module>
    run_script()
  File "RecoverVod.py", line 587, in run_script
    recover_all_clips()
  File "RecoverVod.py", line 403, in recover_all_clips
    with open(generate_log_filename(streamer, vod_id), "w") as log_file:
FileNotFoundError: [Errno 2] No such file or directory: '~\\Documents\\/loltyler1_47302704813_log.txt'

**Comment by jakethewake** [comment]
The reason why i think it's adding the "/" is because linux uses forward slashes instead of back slashes.
For example this is the path to my document folder "~/Documents/" as opposed to the scripts "~\\Documents\\"

**Comment by ItIckeYd** [comment]
@jakethewake interesting... I did not know that. Learn something new everyday 👍 I also don't have much or really any experience with linux so that plays a part.
