### ISSUE TITLE
Modules not found error

### ISSUE THREAD

**Issue by TennisMexican** [ItIckeYd/VodRecovery#81]
I have Python v3.10.6 installed and ran the "pip install -r requirements.txt" after getting the latest code but whenever I try to run the script, it keeps telling me "import grequests ModuleNotFoundError: No module named 'grequests'".

When I do a pip list, I can see that it's clearly installed:
beautifulsoup4     4.11.1
bs4                0.0.1
certifi            2021.10.8
cffi               1.15.1
charset-normalizer 2.0.6
colorama           0.4.5
decorator          4.4.2
gevent             22.10.1
greenlet           1.1.3.post0
grequests          0.6.0
idna               3.2
imageio            2.22.1
imageio-ffmpeg     0.4.7
moviepy            1.0.3
natsort            8.2.0
numpy              1.23.2
Pillow             9.2.0
pip                22.2.2
proglog            0.1.10
pycparser          2.21
requests           2.27.1
soupsieve          2.3.2.post1
torch              1.12.1+cu116
torchaudio         0.12.1+cu116
torchvision        0.13.1+cu116
tqdm               4.64.1
typing_extensions  4.3.0
urllib3            1.26.7
zope.event         4.5.0
zope.interface     5.5.0

Any suggestions?

**Comment by ItIckeYd** [comment]
@TennisMexican If you have an pycharm or a similar IDE installed.. simply hover over the grequests import and it will give you the option to install the package which should fix the issue.

**Comment by TennisMexican** [comment]
Thanks, I was using Visual Studio Code but that apparently wasn't telling me to install. Switched to pycharm and got it working!
