### ISSUE TITLE
ModuleNotFoundError: No module named 'grequests'

### ISSUE THREAD

**Issue by cedric12354** [ItIckeYd/VodRecovery#89]
![123123123](https://user-images.githubusercontent.com/62685240/198479261-74ad7906-2a99-48e3-9b46-85070917a52c.PNG)

**Comment by cedric12354** [comment]
No matter what i do i can't download that module

**Comment by ItIckeYd** [comment]
@cedric12354 Are you using pycharm?

**Comment by cedric12354** [comment]
yes i use PyCharm 2022.2.3

**Comment by ItIckeYd** [comment]
@cedric12354 Simply hover over the import and it will give you the option to install

**Comment by cedric12354** [comment]
thats why i tryed but it didn't work
![123123123](https://user-images.githubusercontent.com/62685240/198495735-a4bae178-e4e1-4d34-8b9a-17b923a85139.PNG)

**Comment by ItIckeYd** [comment]
@cedric12354 

Please make sure of the following: 

 because grequests leverages gevent (which in turn uses monkeypatching for enabling concurrency), you will often need to make sure grequests is imported before other libraries, especially requests, to avoid problems.

**Comment by cedric12354** [comment]
Ok thanks.
But how do i deinstall all of the other libraries so i can install grequests first ?

**Comment by ItIckeYd** [comment]
@cedric12354 

On the bottom you will see 'python packages' click it.. select the package you want to remove.. click the ellipsis on the right and click delete package.

See screenshot... things are highlighted to make it easier.
![github_pycharm](https://user-images.githubusercontent.com/86701308/198497039-63367f8c-ea21-472e-8a2f-e540e8eea881.png)

**Comment by cedric12354** [comment]
Just the "request" one or everything that i have.
I would like to do that over Discord if you have that. cause i am not the best at this and that would make things easier for both of us.
Discord ID: Cedricc_TV#8874

**Comment by cedric12354** [comment]
uninstalled everything and it still didn't work

**Comment by ItIckeYd** [comment]
Due to the issue being solely dependent on proper installation of modules and nothing to do with the script...  this is not in my scope of troubleshooting.

Closing issue.
