### ISSUE TITLE
File "/home/nico/VodRecovery/RecoverVod.py", line 662, in <module>     run_script()   File "/home/nico/VodRecovery/RecoverVod.py", line 635, in run_script   

### ISSUE THREAD

**Issue by B4nny2866** [ItIckeYd/VodRecovery#90]
Hey so the tool is great it recovers vods from streamscharts and twitch tracker perfectly, but sadly i got a little issue and don´t know how to fix it. it´s happening when recovering clips.
Full error message here ->

Do you want to log results to file (Y/N): Y
Traceback (most recent call last):
  File "/home/nico/VodRecovery/RecoverVod.py", line 662, in <module>
    run_script()
  File "/home/nico/VodRecovery/RecoverVod.py", line 635, in run_script
    recover_all_clips()
  File "/home/nico/VodRecovery/RecoverVod.py", line 451, in recover_all_clips
    with open(generate_log_filename(streamer, vod_id), "w") as log_file:
FileNotFoundError: [Errno 2] No such file or directory: '~\\Documents\\/ItsNatashaFFS_29074959424_log.txt'
Thanks in advance.

**Comment by ItIckeYd** [comment]
@B4nny2866 Are you on linux by any chance? and could you provide the input please?

**Comment by B4nny2866** [comment]
hey i´m on linux. so what i first did was literally just print the clips links to the console (removing the log file code) now i tried the fix you suggested.Changing the source code to ~/Documents/ and it worked.

**Comment by B4nny2866** [comment]
ty <3

**Comment by ItIckeYd** [comment]
@B4nny2866 Ill make the update to the code.. so it will work on linux and windows.
