### ISSUE TITLE
Clip duration

### ISSUE THREAD

**Issue by handykop** [ItIckeYd/VodRecovery#93]
Hello,

i noticed when bulk or single recovering clips that all the clips are 26-30 seconds long not shorter or longer,
when trying to recover clips from a channel that has clips that are for example 16 seconds or even a full minute long
it still only recovers 26-30 second long clips, is this a known issue/limitation?

**Comment by ItIckeYd** [comment]
@handykop Clips that are named by the user or have the following format AT-cm[Random numeric and alphabetical string]  I cannot get. Those clips require Twitch API... which I do not use in this application.
